---
title: "Class 1"
output: html_notebook
---

## Init

```{r, echo=FALSE}
library(tidyverse)
```

## Dataset import

```{r}
hand1994_babies <- read_csv("data/hand1994_babies.csv", 
    col_types = cols(Survival = col_factor(levels = c("no", 
        "yes"))))

hand1994_elderheight <- read_lines("data/hand1994_elderheight.csv") %>%
  str_split_fixed(" ", n = Inf) %>%
  as.numeric %>%
  na.omit()

hand1994_snore <- read_csv("data/hand1994_snore.csv", 
    quote = "\\\"", )
```

## Question 1

Make a Two-way table of the hand1994_babies dataset.

```{r}
summary(hand1994_babies) # Dataset summary
```

```{r}
hand1994_babies %>% # Make incidence table
  mutate(Weight = cut_interval(Weight, 5)) %>% # Bin Weight in 5 intervals
  count(Survival, Weight) %>% # Count of each pair case
  group_by(Weight) %>% # Set Weight as exp. variable
  spread(Survival, n, fill = 0) # Make Survival as columns
```

```{r}
hand1994_babies %>% # Make prevalence table
  mutate(Weight = cut_interval(Weight, 5)) %>% # Bin Weight in 5 intervals
  count(Survival, Weight) %>% # Count of each pair case
  group_by(Weight) %>% # Set Weight as exp. variable
  mutate(prop = round(n / sum(n), 2)) %>% # Calc proportion
  select(-n) %>% # Remove pair incidence
  spread(Survival, prop, fill = 0) # Make Survival as columns
```

## Question 4

Analyze hand1994_elderheight dataset.

```{r}
summary(hand1994_elderheight) # Dataset summary
```

```{r}
length(hand1994_elderheight) # Total incidence
```

```{r}
hand1994_elderheight %>% # Binned incidence
  data.frame() %>%
  transmute(Height = cut_width(.,5)) %>% # Bin Height in 5 cm intervals
  count(Height)
```

## Question 5

Complete the prevalence two-way table of the hand1994_snore dataset.

```{r}
hand1994_snore
```

```{r}
hand1994_snore %>% # Snoring as exp. variables:
  mutate(Total = Sim+Nao,
         Sim = Sim/Total,
         Nao = Nao/Total, Total = 1)
```

```{r}
hand1994_snore %>% # Snoring as exp. variables:
  pivot_longer(-`Ronco noturno`, names_to = "Doenca cardiaca") %>% # Dataframe rotation
  pivot_wider(names_from = `Ronco noturno`) %>%
  mutate(Total = Nao+Ocasional+`Quase todas as noites`+Sempre,
         Nao = Nao/Total,
         Ocasional = Ocasional/Total,
         `Quase todas as noites` = `Quase todas as noites`/Total,
         Sempre = Sempre/Total,
         Total = 1)
```
